/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;

/**
 *
 * @author walbonis1
 */
public class Aerolinea extends javax.swing.JFrame {

    /**
     * Creates new form Aerolinea
     */
    String ruta;
    public Aerolinea() {
        initComponents();
        ruta = "src/datos/personas.txt";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOpciones = new javax.swing.JMenu();
        MnReportes = new javax.swing.JMenu();
        MnListados = new javax.swing.JMenu();
        MnListadoCompleto = new javax.swing.JMenuItem();
        MnListadoPorOrigen = new javax.swing.JMenuItem();
        MnCantidades = new javax.swing.JMenu();
        MnNoPasajeros = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();
        MnPasajeros = new javax.swing.JMenu();
        mnagregar = new javax.swing.JMenuItem();
        MnDestino = new javax.swing.JMenu();
        MnAgregarDestino = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aerolinea All Star");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Aerolinea.PNG"))); // NOI18N
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 780, -1));

        mnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479248415_vector_66_14.png"))); // NOI18N
        mnOpciones.setText("Opciones");
        mnOpciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479248417_vector_66_14.png"))); // NOI18N

        MnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479248956_reports.png"))); // NOI18N
        MnReportes.setText("Reportes");

        MnListados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249041_list-alt.png"))); // NOI18N
        MnListados.setText("Listados");

        MnListadoCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479248987_sign-up.png"))); // NOI18N
        MnListadoCompleto.setText("Listado Completo");
        MnListadoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnListadoCompletoActionPerformed(evt);
            }
        });
        MnListados.add(MnListadoCompleto);

        MnListadoPorOrigen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249186_travel_journey-15.png"))); // NOI18N
        MnListadoPorOrigen.setText("Listado Por Origen");
        MnListadoPorOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnListadoPorOrigenActionPerformed(evt);
            }
        });
        MnListados.add(MnListadoPorOrigen);

        MnReportes.add(MnListados);

        MnCantidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249120_kuser.png"))); // NOI18N
        MnCantidades.setText("Cantidades");

        MnNoPasajeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249224_adult-children.png"))); // NOI18N
        MnNoPasajeros.setText("Numero de Pasajeros");
        MnNoPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnNoPasajerosActionPerformed(evt);
            }
        });
        MnCantidades.add(MnNoPasajeros);

        MnReportes.add(MnCantidades);

        mnOpciones.add(MnReportes);
        mnOpciones.add(jSeparator2);

        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479248658_exit.png"))); // NOI18N
        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnOpciones.add(mnSalir);

        jMenuBar1.add(mnOpciones);

        MnPasajeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479248737_taxi_passanger.png"))); // NOI18N
        MnPasajeros.setText("Pasajeros");

        mnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479248875_user-group-new.png"))); // NOI18N
        mnagregar.setText("Agregar");
        mnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnagregarActionPerformed(evt);
            }
        });
        MnPasajeros.add(mnagregar);

        jMenuBar1.add(MnPasajeros);

        MnDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249263_resolutions-21.png"))); // NOI18N
        MnDestino.setText("Destino");

        MnAgregarDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249350_plane-up.png"))); // NOI18N
        MnAgregarDestino.setText("Agregar");
        MnAgregarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAgregarDestinoActionPerformed(evt);
            }
        });
        MnDestino.add(MnAgregarDestino);

        jMenuBar1.add(MnDestino);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(786, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnagregarActionPerformed
    Agregar a = new Agregar(this,true);
        a.setVisible(true);
    }//GEN-LAST:event_mnagregarActionPerformed

    private void MnListadoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnListadoCompletoActionPerformed
     ListadoCompleto lc = new ListadoCompleto(this,true);
        lc.setVisible(true);
    }//GEN-LAST:event_MnListadoCompletoActionPerformed

    private void MnListadoPorOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnListadoPorOrigenActionPerformed
    ListadoPorOrigen lpo = new ListadoPorOrigen(this,true);
    lpo.setVisible(true);
    }//GEN-LAST:event_MnListadoPorOrigenActionPerformed

    private void MnNoPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnNoPasajerosActionPerformed
    int cont;
        cont = Helper.traerDatos(ruta).size();
        Helper.mensaje(this, "El número de pasajeros ingresados es: "+cont, 1);
    }//GEN-LAST:event_MnNoPasajerosActionPerformed

    private void MnAgregarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAgregarDestinoActionPerformed
    AgregarDestino ad = new AgregarDestino(this,true);
        ad.setVisible(true); 
    }//GEN-LAST:event_MnAgregarDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aerolinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnAgregarDestino;
    private javax.swing.JMenu MnCantidades;
    private javax.swing.JMenu MnDestino;
    private javax.swing.JMenuItem MnListadoCompleto;
    private javax.swing.JMenuItem MnListadoPorOrigen;
    private javax.swing.JMenu MnListados;
    private javax.swing.JMenuItem MnNoPasajeros;
    private javax.swing.JMenu MnPasajeros;
    private javax.swing.JMenu MnReportes;
    private javax.swing.JLabel imagen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnagregar;
    // End of variables declaration//GEN-END:variables
    }
