/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Destino;
import clases.Helper;
import clases.Personas;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author karrieta9
 */
public class AgregarEdad extends javax.swing.JDialog {

    /**
     * Creates new form AgregarEdad
     */
    String rutaD, rutaP;

    ObjectOutputStream salida;
    ArrayList<Destino> destinos;
    int aux = 0;
    public AgregarEdad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JButton botonesH[] = {cmdCancelar,cmdBuscar };
        JButton botonesD[] = {cmdEliminar, cmdGuardar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        rutaP = "src/datos/personas.txt";
        rutaD = "src/datos/destino.txt";
        Helper.llenarComboPersonas(cmbPasajeros, rutaP);
        try {
            destinos = Helper.traerDatos(rutaD);
            salida = new ObjectOutputStream(new FileOutputStream(rutaD));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, destinos);
        Helper.llenarTablaDestino(tblDestinos, rutaD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Edad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ToggleButtonAnciano = new javax.swing.JToggleButton();
        ToggleButtonBebe = new javax.swing.JToggleButton();
        ToggleButtonNino = new javax.swing.JToggleButton();
        ToggleButtonAdulto = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        cmdBuscar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbPasajeros = new javax.swing.JComboBox();
        txtCedula = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDestinos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Edad:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        Edad.add(ToggleButtonAnciano);
        ToggleButtonAnciano.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ToggleButtonAnciano.setText("Anciano");
        jPanel1.add(ToggleButtonAnciano, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 100, 60));

        Edad.add(ToggleButtonBebe);
        ToggleButtonBebe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ToggleButtonBebe.setText("Bebe");
        jPanel1.add(ToggleButtonBebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 100, 60));

        Edad.add(ToggleButtonNino);
        ToggleButtonNino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ToggleButtonNino.setText("Niño");
        jPanel1.add(ToggleButtonNino, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 100, 60));

        Edad.add(ToggleButtonAdulto);
        ToggleButtonAdulto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ToggleButtonAdulto.setText("Adulto");
        jPanel1.add(ToggleButtonAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249453_system-search.png"))); // NOI18N
        cmdBuscar.setText("Buscar");
        cmdBuscar.setContentAreaFilled(false);
        cmdBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249454_system-search.png"))); // NOI18N
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        cmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249679_save.png"))); // NOI18N
        cmdGuardar.setText("Guardar");
        cmdGuardar.setContentAreaFilled(false);
        cmdGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249681_save.png"))); // NOI18N
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));

        cmdCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249854_Close_Icon.png"))); // NOI18N
        cmdCancelar.setText("Cancelar");
        cmdCancelar.setContentAreaFilled(false);
        cmdCancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249855_Close_Icon.png"))); // NOI18N
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 31, 120, 30));

        cmdEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249785_free-27.png"))); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.setContentAreaFilled(false);
        cmdEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249786_free-27.png"))); // NOI18N
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 480, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Cedula:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        cmbPasajeros.setBackground(new java.awt.Color(0, 102, 255));
        cmbPasajeros.setOpaque(false);
        jPanel3.add(cmbPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 200, -1));

        txtCedula.setForeground(new java.awt.Color(0, 0, 255));
        txtCedula.setOpaque(false);
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel3.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, -1));

        jLabel20.setText("Pasajero:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 300, 90));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Pasajeros"));
        jPanel13.setOpaque(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDestinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Cédula", "Nombre", "Apellido", "Sexo", "Edad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDestinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDestinosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDestinos);

        jPanel13.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 570, 230));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 640, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        String cedula, auxPasajeros;
        Personas pasajeros;
        cedula = txtCedula.getText();
        Destino d;

        if (txtCedula.getText().isEmpty()) {
            getToolkit().beep();
            Helper.mensaje(this, "Digite Numero de su Cedula", 3);
            txtCedula.requestFocusInWindow();
        }

        else{

            if (Helper.buscarDestino(cedula, rutaD)) {
                d = Helper.traerDestino(cedula, rutaD);
                txtCedula.setText(d.getPasajero().getCedula());
                pasajeros = d.getPasajero();
                auxPasajeros = pasajeros.getCedula() + " - " + pasajeros.getNombre() + " " + pasajeros.getApellido();
                cmbPasajeros.setSelectedItem(auxPasajeros);

                aux = 1;
            } else {
                txtCedula.requestFocusInWindow();
                aux = 0;
            }
            JButton botonesH[]={cmdGuardar,cmdCancelar};
            JButton botonesD[]={cmdBuscar, cmdEliminar};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed

        String auxPasajero, cedula,destino;
        int indice;
        Personas pasajeros;

        if (!(ToggleButtonAdulto.isSelected() || ToggleButtonAnciano.isSelected() || ToggleButtonBebe.isSelected() || ToggleButtonNino.isSelected())){
        getToolkit().beep();
        Helper.mensaje(this, "Seleccione su Edad", 3);
        }else{

            destino=Helper.destinoSeleccionado(radioButtonBarranquilla, radioButtonBogota, radioButtonMadrid, radioButtonMiami, radioButtonNuevaYork,
                radioButtonParis, radioButtonRioDeJaneiro, radioButtonSanAndres);
            auxPasajero = cmbPasajeros.getSelectedItem().toString();
            indice = auxPasajero.indexOf("-") - 1;
            cedula = auxPasajero.substring(0, indice);
            ArrayList<Destino> destinosModificado;
            pasajeros = Helper.traerPersonaCedula(cedula, rutaP);
            try {
                if (aux == 0) {

                    Destino d = new Destino(destino, pasajeros);
                    d.guardar(salida);

                } else {
                    destinosModificado = Helper.modificarDestino(rutaD, cedula,destino, pasajeros);
                    salida = new ObjectOutputStream(new FileOutputStream(rutaD));
                    Helper.volcado(salida, destinosModificado);
                    aux = 0;
                    Helper.mensaje(this, "Destino Actualizado Correctamente!", 1);
                }
            } catch (IOException ex) {
                Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
            }

            Helper.llenarTablaDestino(tblDestinos, rutaD);

            cmbPasajeros.setSelectedIndex(0);
            cmdDestino.clearSelection();

            JButton botonesH[] = {cmdCancelar,cmdBuscar };
            JButton botonesD[] = {cmdEliminar, cmdGuardar};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        txtCedula.setText("");
        cmbPasajeros.setSelectedIndex(0);
        cmdDestino.clearSelection();

        JButton botonesH[]={cmdBuscar,cmdCancelar};
        JButton botonesD[]={cmdEliminar,cmdGuardar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int i, op;
        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar a esta persona?", "Eliminar", JOptionPane.YES_NO_OPTION);

        ArrayList<Destino> destinos = Helper.traerDatos(rutaD);
        if (op == JOptionPane.YES_OPTION) {
            i = tblDestinos.getSelectedRow();
            destinos.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(rutaD));
            } catch (FileNotFoundException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
            Helper.volcado(salida, destinos);
            Helper.llenarTablaDestino(tblDestinos, rutaD);
            txtCedula.setText("");

            txtCedula.requestFocusInWindow();
        }
        JButton botonesH[]={cmdBuscar,cmdCancelar};
        JButton botonesD[]={cmdEliminar,cmdGuardar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void tblDestinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDestinosMouseClicked
        int i;
        Destino d;
        ArrayList<Destino> destinoss = Helper.traerDatos(rutaD);
        i = tblDestinos.getSelectedRow();

        d = destinoss.get(i);

        txtCedula.setText(d.getPasajero().getCedula());

        JButton botonesH[]={cmdEliminar};

        Helper.habilitarBotones(botonesH);
    }//GEN-LAST:event_tblDestinosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEdad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEdad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEdad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEdad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarEdad dialog = new AgregarEdad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Edad;
    private javax.swing.JToggleButton ToggleButtonAdulto;
    private javax.swing.JToggleButton ToggleButtonAnciano;
    private javax.swing.JToggleButton ToggleButtonBebe;
    private javax.swing.JToggleButton ToggleButtonNino;
    private javax.swing.JComboBox cmbPasajeros;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDestinos;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
