/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Destino;
import clases.Helper;
import clases.Motivo;
import clases.Personas;
import static interfaz.AgregarDestino.cmdDestino;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author karrieta9
 */
public class definirMotivo extends javax.swing.JDialog {

    /**
     * Creates new form definirMotivo
     */
    String rutaD, rutaP,rutaM;
    ObjectOutputStream salida;
    ArrayList<Motivo> motivos;
    int aux = 0;
   
    public definirMotivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JButton botonesH[] = {cmdCancelar,cmdBuscar,cmdGuardar };
        JButton botonesD[] = {cmdEliminar };

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        rutaP = "src/datos/personas.txt";
        rutaD = "src/datos/destino.txt";
        rutaM = "src/datos/moti.txt";
        Helper.llenarComboPersonas(cmbPasajeros, rutaP);
        try {
            motivos = Helper.traerDatos(rutaM);
            salida = new ObjectOutputStream(new FileOutputStream(rutaM));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, motivos);
        Helper.llenarTablaMotivo(tblPasajeros, rutaM,rutaP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Motivo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbPasajeros = new javax.swing.JComboBox();
        txtCedula = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmdBuscar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        radioButtonNegocios = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        radioButtonTurismo = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        radioButtonEducacion = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        radioButtonFamiliar = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPasajeros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Cedula:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        cmbPasajeros.setBackground(new java.awt.Color(0, 102, 255));
        cmbPasajeros.setOpaque(false);
        jPanel2.add(cmbPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 200, -1));

        txtCedula.setForeground(new java.awt.Color(0, 0, 255));
        txtCedula.setOpaque(false);
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, -1));

        jLabel20.setText("Pasajero:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 300, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249453_system-search.png"))); // NOI18N
        cmdBuscar.setText("Buscar");
        cmdBuscar.setContentAreaFilled(false);
        cmdBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249454_system-search.png"))); // NOI18N
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        cmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249679_save.png"))); // NOI18N
        cmdGuardar.setText("Guardar");
        cmdGuardar.setContentAreaFilled(false);
        cmdGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249681_save.png"))); // NOI18N
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));

        cmdCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249854_Close_Icon.png"))); // NOI18N
        cmdCancelar.setText("Cancelar");
        cmdCancelar.setContentAreaFilled(false);
        cmdCancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249855_Close_Icon.png"))); // NOI18N
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 31, 120, 30));

        cmdEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249785_free-27.png"))); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.setContentAreaFilled(false);
        cmdEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1479249786_free-27.png"))); // NOI18N
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 480, 80));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/acuerdo-de-negocios-de-dibujos-animados_23-2147508090.jpg"))); // NOI18N
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 120));

        Motivo.add(radioButtonNegocios);
        jPanel7.add(radioButtonNegocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Negocios");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, 190));

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Situacion-de-la-industria-del-turismo-andaluz.jpg"))); // NOI18N
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 120));

        Motivo.add(radioButtonTurismo);
        jPanel11.add(radioButtonTurismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel17.setText("Turismo");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 140, 190));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/educacion-gratis-latinoamerica.jpg"))); // NOI18N
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 120));

        Motivo.add(radioButtonEducacion);
        jPanel12.add(radioButtonEducacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel19.setText("Educacion");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, -1));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 140, 190));

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setOpaque(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3092_logo.jpg"))); // NOI18N
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 120));

        Motivo.add(radioButtonFamiliar);
        jPanel13.add(radioButtonFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel22.setText("Familiar");
        jPanel13.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, -1));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 140, 190));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Pasajeros"));
        jPanel14.setOpaque(false);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Cédula", "Nombre", "Apellido", "Motivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPasajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasajerosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPasajeros);

        jPanel14.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 190));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 610, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
       String auxMotivo, cedula,motivo;
        int indice;
        Personas motivos;
        
        if (!(radioButtonEducacion.isSelected() || radioButtonFamiliar.isSelected() || radioButtonNegocios.isSelected() || radioButtonTurismo.isSelected() )){
            getToolkit().beep();
            Helper.mensaje(this, "Seleccione su Motivo", 3);    
        }else{
            
        motivo=Helper.motivoSeleccionado(radioButtonNegocios, radioButtonEducacion, radioButtonFamiliar, radioButtonTurismo);
        
        auxMotivo = cmbPasajeros.getSelectedItem().toString();
        indice = auxMotivo.indexOf("-") - 1;
        cedula = auxMotivo.substring(0, indice);
        ArrayList<Motivo> motivosModificado;
       motivos = Helper.traerPersonaCedula(cedula, rutaP);
        try {
            if (aux == 0) {

                Motivo m = new Motivo(motivo);
                m.guardar(salida);

            } else {
                motivosModificado = Helper.modificarMotivo(rutaM, cedula,motivo);
                salida = new ObjectOutputStream(new FileOutputStream(rutaM));
                Helper.volcado(salida, motivosModificado);
                aux = 0;
                Helper.mensaje(this, "Motivo Actualizado Correctamente!", 1);
            }
        } catch (IOException ex) {
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }

        Helper.llenarTablaMotivo(tblPasajeros, rutaM,rutaP);

       

        cmbPasajeros.setSelectedIndex(0);
        Motivo.clearSelection();
        
        JButton botonesH[] = {cmdCancelar,cmdBuscar };
        JButton botonesD[] = {cmdEliminar, cmdGuardar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
    int i, op;
        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar a esta persona?", "Eliminar", JOptionPane.YES_NO_OPTION);

        ArrayList<Motivo> motivos = Helper.traerDatos(rutaM);
        if (op == JOptionPane.YES_OPTION) {
            i = tblPasajeros.getSelectedRow();
            motivos.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(rutaM));
            } catch (FileNotFoundException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
            Helper.volcado(salida, motivos);
            Helper.llenarTablaMotivo(tblPasajeros, rutaM,rutaP);
            txtCedula.setText("");
            
          
          
            txtCedula.requestFocusInWindow();
        }
        JButton botonesH[]={cmdBuscar,cmdCancelar};
        JButton botonesD[]={cmdEliminar,cmdGuardar};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        
        
        
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void tblPasajerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasajerosMouseClicked
    int i;
        Destino d;
        ArrayList<Destino> destinoss = Helper.traerDatos(rutaD);
        i = tblPasajeros.getSelectedRow();

        d = destinoss.get(i);

        txtCedula.setText(d.getPasajero().getCedula());

        JButton botonesH[]={cmdEliminar};
        
        Helper.habilitarBotones(botonesH);
    }//GEN-LAST:event_tblPasajerosMouseClicked

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
    txtCedula.setText("");
        cmbPasajeros.setSelectedIndex(0);
        Motivo.clearSelection();
        
         JButton botonesH[]={cmdBuscar,cmdCancelar};
        JButton botonesD[]={cmdEliminar,cmdGuardar};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
    String cedula, auxPasajeros;
        Personas pasajeros;
        cedula = txtCedula.getText();
        Destino d;
        
        if (txtCedula.getText().isEmpty()) {
            getToolkit().beep();
            Helper.mensaje(this, "Digite Numero de su Cedula", 3);
            txtCedula.requestFocusInWindow();
        }
        
        else{
        
        if (Helper.buscarDestino(cedula, rutaD)) {
            d = Helper.traerDestino(cedula, rutaD);
            txtCedula.setText(d.getPasajero().getCedula());
            pasajeros = d.getPasajero();
            auxPasajeros = pasajeros.getCedula() + " - " + pasajeros.getNombre() + " " + pasajeros.getApellido();
            cmbPasajeros.setSelectedItem(auxPasajeros);
          
            
            aux = 1;
        } else {
            txtCedula.requestFocusInWindow();
            aux = 0;
        }
       JButton botonesH[]={cmdGuardar,cmdCancelar};
        JButton botonesD[]={cmdBuscar, cmdEliminar};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(definirMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(definirMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(definirMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(definirMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                definirMotivo dialog = new definirMotivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Motivo;
    private javax.swing.JComboBox cmbPasajeros;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioButtonEducacion;
    private javax.swing.JRadioButton radioButtonFamiliar;
    private javax.swing.JRadioButton radioButtonNegocios;
    private javax.swing.JRadioButton radioButtonTurismo;
    private javax.swing.JTable tblPasajeros;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
