/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author walbonis1
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOpciones = new javax.swing.JMenu();
        mnagregar = new javax.swing.JMenuItem();
        MnReportes = new javax.swing.JMenu();
        MnListados = new javax.swing.JMenu();
        MnListadoCompleto = new javax.swing.JMenuItem();
        MnListadoPorOrigen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aerolinea All Star");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Aerolinea.PNG"))); // NOI18N
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 780, -1));

        mnOpciones.setText("Opciones");

        mnagregar.setText("Agregar");
        mnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnagregarActionPerformed(evt);
            }
        });
        mnOpciones.add(mnagregar);

        MnReportes.setText("Reportes");

        MnListados.setText("Listados");

        MnListadoCompleto.setText("Listado Completo");
        MnListadoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnListadoCompletoActionPerformed(evt);
            }
        });
        MnListados.add(MnListadoCompleto);

        MnListadoPorOrigen.setText("Listado Por Origen");
        MnListadoPorOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnListadoPorOrigenActionPerformed(evt);
            }
        });
        MnListados.add(MnListadoPorOrigen);

        MnReportes.add(MnListados);

        mnOpciones.add(MnReportes);
        mnOpciones.add(jSeparator1);

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnOpciones.add(mnSalir);

        jMenuBar1.add(mnOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(786, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnagregarActionPerformed
    Agregar a = new Agregar(this,true);
        a.setVisible(true);
    }//GEN-LAST:event_mnagregarActionPerformed

    private void MnListadoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnListadoCompletoActionPerformed
     ListadoCompleto lc = new ListadoCompleto(this,true);
        lc.setVisible(true);
    }//GEN-LAST:event_MnListadoCompletoActionPerformed

    private void MnListadoPorOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnListadoPorOrigenActionPerformed
    ListadoPorOrigen lpo = new ListadoPorOrigen(this,true);
    lpo.setVisible(true);
    }//GEN-LAST:event_MnListadoPorOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnListadoCompleto;
    private javax.swing.JMenuItem MnListadoPorOrigen;
    private javax.swing.JMenu MnListados;
    private javax.swing.JMenu MnReportes;
    private javax.swing.JLabel imagen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnagregar;
    // End of variables declaration//GEN-END:variables
    }
